### PR TITLE
Fix "Should not sleep" to catch world.Export and world.Import

### LINKED ISSUE #208: "Should not sleep" does not catch world.Export or world.Import

### PR DESCRIPTION
**Pull request by spookydonut**
Fixes #208

### CODE REVIEW

File: src/dreamchecker/lib.rs [hunk 1]
```diff
@@ -1702,10 +1702,13 @@ impl<'o, 's> AnalyzeProc<'o, 's> {
...
 
             Term::Call(unscoped_name, args) => {
-                if unscoped_name == "sleep" || unscoped_name == "alert" || unscoped_name == "shell" || unscoped_name == "winexists" || unscoped_name == "winget" {
-                    if self.inside_newcontext == 0 {
+                if matches!(unscoped_name.as_str(),
+                    "sleep"
+                    | "alert"
+                    | "shell"
+                    | "winexists"
+                    | "winget" if self.inside_newcontext == 0) {
```
Comment (SpaceManiac) [inline src/dreamchecker/lib.rs:1710]: style nit: the `if` guard doesn't depend on the pattern, so it should probably go outside the `matches!()` invocation

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
also test doesn't pass

File: src/dreamchecker/lib.rs (hunk 1 above)
Comment (spookydonut) [reply src/dreamchecker/lib.rs:1710]: true
