### PR TITLE
Fixes ';' in proc args causing parse failure

### LINKED ISSUE #172: ; in proc arguments causes a fatal parse error
https://github.com/PolarisSS13/Polaris/pull/6941

### PR DESCRIPTION
**Pull request by Cyberboss**
Optionally allow trailing `;`s after the expression in proc arguments. Emit a warning when doing so.

Added ast_tests.

Fixes #172

### CODE REVIEW

File: src/dreammaker/tests/ast_tests.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    f(context, _tree)
+}
+
+#[test]
+fn check_semicolon_in_proc_parameters() {
+    with_code("
+#define SOMESHIT 0x01;
+#define SUMFUCK \"asdf\" as text;
+
+/proc/fuck(foo = SOMESHIT, bar = SUMFUCK, anotherarg = 1)
```
Comment (SpaceManiac) [inline src/dreammaker/tests/ast_tests.rs:25]: SFW naming please
